Quiron.LojaVirtual.Web/Models/CarrinhoViewModel.cs
using Quiron.LojaVirtual.Dominio.Entidade;

namespace Quiron.LojaVirtual.Web.Models
{
    public class CarrinhoViewModel
    {
        public Carrinho Carrinho { get; set; }
        public string ReturnUrl { get; set; }

    }
}

Quiron.LojaVirtual.Web/Models/Paginacao.cs
using System;

namespace Quiron.LojaVirtual.Web.Models
{
    public class Paginacao
    {
        public int ItensTotal { get; set; }
        public int ItensPorPagina { get; set; }
        public int PaginaAtual { get; set; }
        public int TotalPagina 
        {
            get
            {
                return (int)Math.Ceiling((decimal)ItensTotal / ItensPorPagina);
            }
        }
    }
}

Quiron.LojaVirtual.Web/Models/ProdutosViewModel.cs
using Quiron.LojaVirtual.Dominio.Entidade;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Quiron.LojaVirtual.Web.Models
{
    public class ProdutosViewModel
    {
        public IEnumerable<Produto> Produtos { get; set; }

        public Paginacao Paginacao { get; set; }

        public string CategoriaAtual { get; set; }

    }
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Controllers/ProdutoController.cs
using Quiron.LojaVirtual.Dominio.Entidade;
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Areas.Administrativo.Controllers
{
    public class ProdutoController : Controller
    {
        private ProdutosRepositorio _repositorio;

        // GET: Administrativo/Produto
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.Produtos;

            return View(produtos);
        }

        public ViewResult Alterar(int produtoId)
        {
            _repositorio = new ProdutosRepositorio();
            Produto produto = _repositorio.Produtos
                .FirstOrDefault(p => p.ProdutoId == produtoId);
            return View(produto);
        }

        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            if (ModelState.IsValid)
            {
                _repositorio = new ProdutosRepositorio();
                _repositorio.Salvar(produto);

                TempData["mensagem"] = string.Format("{0} foi salvo com sucesso", produto.Nome);

                return RedirectToAction("Index");

            }
            return View(produto);
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/CarrinhoController.cs
using Quiron.LojaVirtual.Dominio.Entidade;
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CarrinhoController : Controller
    {
        private ProdutosRepositorio _repositorio;
        
        public CarrinhoController()
        {
            _repositorio = new ProdutosRepositorio();
        }

        public RedirectToRouteResult Adicionar(int produtoId, string returnUrl)
        {            
            Produto produto = _repositorio.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);

            if(produto != null)
            {
                ObterCarrinho().AdicionarItem(produto, 1);
            }

            return RedirectToAction("Index", new { returnUrl });

        }

        private Carrinho ObterCarrinho()
        {
            Carrinho carrinho = (Carrinho) Session["Carrinho"];

            if (carrinho == null)
            {
                carrinho = new Carrinho();
                Session["Carrinho"] = carrinho;
            }

            return carrinho;
        }

        public RedirectToRouteResult Remover(int produtoId, string returnUrl)
        {
            Produto produto = _repositorio.Produtos.FirstOrDefault(p => p.ProdutoId == produtoId);

            if (produto != null)
            {
                ObterCarrinho().RemoverItem(produto);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CarrinhoViewModel
            {
                Carrinho = ObterCarrinho(),
                ReturnUrl = returnUrl
            });
        }

        public PartialViewResult Resumo()
        {
            Carrinho carrinho = ObterCarrinho();
            return PartialView(carrinho);
        }

        public ViewResult FecharPedido()
        {
            return View(new Pedido());
        }

        [HttpPost]
        public ViewResult FecharPedido(Pedido pedido)
        {
            Carrinho carrinho = ObterCarrinho();
            EmailConfiguracoes email = new EmailConfiguracoes
            { 
                EscreverArquivo = bool.Parse(ConfigurationManager.AppSettings["Email.EscreverArquivo"] ?? "false")
            };

            EmailPedido emailPedido = new EmailPedido(email);

            if (!carrinho.ItensCarrinho.Any())
            {
                ModelState.AddModelError("", "Não foi possível concluir o pedido, seu carrinho está vazio!");
            }

            if (ModelState.IsValid)
            {
                emailPedido.ProcessarPedido(carrinho, pedido);
                carrinho.LimparCarrinho();
                return View("PedidoConcluido");
            }
            else
            {
                return View(pedido);
            }

        }

        public ViewResult PedidoConcluido()
        {
            return View();
        }


    }
}

Quiron.LojaVirtual.Web/Controllers/CategoriaController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class CategoriaController : Controller
    {
        private ProdutosRepositorio _repositorio;

        // GET: Categoria
        public PartialViewResult Menu(string categoria = null)
        {
            ViewBag.CategoriaSelecionada = categoria;
            _repositorio = new ProdutosRepositorio();

            IEnumerable<String> categorias = _repositorio.Produtos
                .Select(c => c.Categoria)
                .Distinct()
                .OrderBy(c => c);


            return PartialView(categorias);
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/ProdutosController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{   

    public class ProdutosController : Controller
    {
        private ProdutosRepositorio _repositorio;

        // GET: Produtos
        public ActionResult Index()
        {
            _repositorio = new ProdutosRepositorio();
            var produtos = _repositorio.Produtos.Take(10);

            return View(produtos);
        }
    }
}

Quiron.LojaVirtual.Web/Controllers/VitrineController.cs
using Quiron.LojaVirtual.Dominio.Repositorio;
using Quiron.LojaVirtual.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Quiron.LojaVirtual.Web.Controllers
{
    public class VitrineController : Controller
    {
        private ProdutosRepositorio _repositorio;
        public int ProdutosPorPagina = 5;

        // GET: Vitrine
        public ActionResult ListaProdutos(string categoria, int pagina = 1)
        {
            _repositorio = new ProdutosRepositorio();
            ProdutosViewModel model = new ProdutosViewModel
            {
                Produtos = _repositorio.Produtos
                .Where(p => categoria == null || p.Categoria == categoria)
                .OrderBy(p => p.Descricao)
                .Skip((pagina - 1) * ProdutosPorPagina)
                .Take(ProdutosPorPagina),

                Paginacao = new Paginacao
                {
                    PaginaAtual = pagina,
                    ItensPorPagina = ProdutosPorPagina,
                    ItensTotal = _repositorio.Produtos.Count()
                },

                CategoriaAtual = categoria
            };           

            return View(model);
        }
    }
}

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Alterar.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Produto


@{
    ViewBag.Title = "Alterar - " + @Model.Nome;
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Alterar - @Model.Nome</h3>
    </div>

    @using(Html.BeginForm())
    {
        <div class="panel-body">
            @Html.HiddenFor(m => m.ProdutoId)

            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if(property.PropertyName != "ProdutoId")
                {
                    <div class="form-group">
                    <label>@(property.DisplayName ?? property.PropertyName) </label>
                

                    @if (property.PropertyName == "Descricao") 
                    { 
                        @Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = 5 })
                    }
                    else 
                    { 
                        @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                    }

                </div>
                }
                
            }
        </div>

        <div class="panel-footer">
            <input type="submit" value="Salvar" class="btn btn-primary" />

            @Html.ActionLink("Cancelar e retornar", "Index", null, new {  @class = "btn btn-default"})
        </div>
    }
</div>

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Produto/Index.cshtml
@model IEnumerable<Quiron.LojaVirtual.Dominio.Entidade.Produto>


@{
    ViewBag.Title = "Administrativo - Produtos";
    Layout = "~/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml";
}


<div class="panel panel-default">

    <div class="panel-heading">
        <h3>Quiron Loja Virtual - Administrativo - Produtos</h3>
    </div>

    <div class="panel-body">

        @Html.ActionLink("Novo produto", "NovoProduto", "Produto", new { @class = "btn btn-default" })

        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th class="text-right">#Id</th>
                    <th>Nome</th>
                    <th class="text-right">Preço</th>
                    <th class="text-center">Excluir</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr id="row-@item.ProdutoId">

                        <td class="text-right">
                            #  @item.ProdutoId
                        </td>
                        <td>
                            @Html.ActionLink(item.Nome, "Alterar", new { item.ProdutoId })
                        </td>
                        <td class="text-right">
                            @item.Preco.ToString("c")
                        </td>

                        <td class="text-center">

                            @using (Html.BeginForm("Excluir", "Produto"))
                            {
                                @Html.Hidden("ProdutoId", item.ProdutoId)

                                <input type="submit" class="btn btn-default btn-xs" value="Excluir" />
                            }

                        </td>
                    </tr>
                }

            </tbody>
        </table>

    </div>
</div>

Quiron.LojaVirtual.Web/Areas/Administrativo/Views/Shared/_AdministrativoLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quiron - Administrativo</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErroEstilo.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


</head>
<body>   

        <div>
            @if(TempData["Mensagem"] != null)
            {
                <div class="alert alert-success">@TempData["Mensagem"]</div>
            }

            @RenderBody()

        </div>
    
</body>
</html>

Quiron.LojaVirtual.Web/Views/Carrinho/FecharPedido.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Pedido

@{
    ViewBag.Title = "Quiron: Fechar o pedido";
}

<h2>Fechar o pedido</h2>

<p>Digite suas informações abaixo</p>


@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <h3>Enviar para</h3>

    <div class="form-group">
        <label>Nome do cliente:</label>
        @Html.TextBoxFor(x => x.NomeCliente, new { @class = "form-control" })
    </div>
    
    <h3>Dados para entrega</h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "NomeCliente" && property.PropertyName != "EmbrulhaPresente")
        {
            <div class="form-group">

                <label>
                    @(property.DisplayName ?? property.PropertyName)
                </label>

                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })

            </div>
        }
    }

    <h3>Opções</h3>
    <div class="checkbox">
        <label>
           @Html.EditorFor(x => x.EmbrulhaPresente)
            Embrulhar para presente?
        </label>
    </div>

    <input class="btn btn-primary" type="submit" value="Fechar o pedido"/>
}


<script src="~/Scripts/jquery-3.5.1.min.js"></script>

<script>
    $(document).ready(function () {

        function limpa_formulario_cep() {
            $('#Endereco').val('');
            $('#Bairro').val('');
            $('#Cidade').val('');
            $('#Estado').val('');
        }

        $('#Cep').change(function (e) {
            e.preventDefault();

            limpa_formulario_cep();

            //Nova variável "cep" somente com dígitos.
            var cep = $(this).val().replace(/\D/g, '');

            if (cep != "")
            {
                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;

                //Valida o formato do CEP.
                if (validacep.test(cep))
                {
                    //Preenche os campos com "..." enquanto consulta webservice.
                    $('#Endereco').val('...');
                    $('#Bairro').val('...');
                    $('#Cidade').val('...');
                    $('#Estado').val('...');

                    //Consulta o webservice viacep.com.br/
                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {

                        if (!("erro" in dados)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#Endereco").val(dados.logradouro);
                            $("#Bairro").val(dados.bairro);
                            $("#Cidade").val(dados.localidade);
                            $("#Estado").val(dados.uf);
                        } //end if.
                        else {
                            //CEP pesquisado não foi encontrado.
                            limpa_formulario_cep();
                            alert("CEP não encontrado.");
                        }
                    });
                }
                else
                {
                    //cep é inválido.
                    limpa_formulario_cep();
                    alert("Formato de CEP inválido.");
                }

            }

           
        });

    });

    
</script>

Quiron.LojaVirtual.Web/Views/Carrinho/Index.cshtml
@model Quiron.LojaVirtual.Web.Models.CarrinhoViewModel

@{
    ViewBag.Title = "Quiron: Seu carrinho";
}

<style>
    #carrinhoTable td {
        vertical-align: middle;
    }
</style>

<h2>Seu Carrinho</h2>
<table id="carrinhoTable" class="table">
    <thead>
        <tr>
            <th>Quantidade</th>
            <th>Produto</th>
            <th class="text-right">Preço</th>
            <th class="text-right">SubTotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Carrinho.ItensCarrinho)
        {
        <tr>
            <td class="text-center">@item.Quantidade</td>
            <td class="text-center">@item.Produto.Nome</td>
            <td class="text-right">@item.Produto.Preco.ToString("c")</td>
            <td class="text-right">@((item.Quantidade * item.Produto.Preco).ToString("c"))</td>
            <td>
                @using (Html.BeginForm("Remover", "Carrinho"))
                {
                    @Html.Hidden("ProdutoId", item.Produto.ProdutoId)
                    @Html.HiddenFor(x => x.ReturnUrl) 
                    <input class="btn btn-sm btn-warning" type="submit" value="Remover" />
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Carrinho.ObterValorTotal().ToString("c")
            </td>
        </tr>
    </tfoot>

</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">
        Continuar comprando
    </a>
    @Html.ActionLink("Fechar o pedido", "FecharPedido", "Carrinho", new { @class = "btn btn-primary" })
</div>

Quiron.LojaVirtual.Web/Views/Carrinho/PedidoConcluido.cshtml
@{ 
    ViewBag.Title = "Pedido Concluído";
}

<h2>Obrigado!</h2>

Obrigado pela sua compra, iremos enviar o pedido o mais rápido possível.

Quiron.LojaVirtual.Web/Views/Carrinho/Resumo.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Carrinho

<div class="navbar-right">
    @Html.ActionLink("Checkout", "Index", "Carrinho", new { returnUrl = Request.Url.PathAndQuery }, new { @class= "btn btn-default navbar-btn"})
</div>
<div class="navbar-text navbar-right">
    <b>Seus produtos:</b>
    @Model.ItensCarrinho.Sum(x => x.Quantidade) item(s), @Model.ObterValorTotal().ToString("c")
</div>

Quiron.LojaVirtual.Web/Views/Categoria/Menu.cshtml
@model System.Collections.Generic.IEnumerable<string>

@Html.ActionLink("Todos os produtos", "ListaProdutos", "Vitrine", null, new { @class = "btn btn-block btn-default btn-lg" })


@foreach (var link in Model)
{
@Html.RouteLink(link, new
{
    controller = "Vitrine",
    action = "ListaProdutos",
    categoria = link,
    pagina = 1
}, new
{
    @class = "btn btn-block btn-default btn-lg"
        + (link == ViewBag.CategoriaSelecionada ? " btn-primary" : "")
})}

Quiron.LojaVirtual.Web/Views/Produtos/Index.cshtml
@model IEnumerable<Quiron.LojaVirtual.Dominio.Entidade.Produto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Categoria)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Categoria)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProdutoId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProdutoId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProdutoId })
        </td>
    </tr>
}

</table>

Quiron.LojaVirtual.Web/Views/Shared/ProdutoDetalhes.cshtml
@model Quiron.LojaVirtual.Dominio.Entidade.Produto

<div class="well">

    <h3><strong>@Model.Nome</strong></h3>
    <h3><span class="pull-right label label-primary">@Model.Preco.ToString("c")</span></h3>

    @using (Html.BeginForm("Adicionar", "Carrinho"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProdutoId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Comprar" />
        </div>
    }

    <h3><span class="lead">@Model.Descricao</span></h3>

</div>

Quiron.LojaVirtual.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Quiron Loja Virtual</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/ErroEstilo.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Quiron Loja Virtual - Seu esporte é aqui", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Sair</a></li>
                </ul>
            </div>
        </div>
    </div>*@

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <a class="navbar-brand">Quiron Loja Virtual - Seu esporte é aqui</a>
        @Html.Action("Resumo","Carrinho")
    </div>
    <div class="row panel"></div>
    <div class="row panel">
        <div id="categorias" class="col-xs-3">
            @Html.Action("Menu", "Categoria")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>

    @*<div class="container body-content">
       
        @RenderBody()
        <hr />
    </div>*@

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Quiron.LojaVirtual.Web/Views/Vitrine/ListaProdutos.cshtml
@model Quiron.LojaVirtual.Web.Models.ProdutosViewModel
@using Quiron.LojaVirtual.Web.HtmlHelpers
 

@{
    ViewBag.Title = "ListaProdutos";
}

    @foreach (var p in Model.Produtos)
    {
             @Html.Partial("ProdutoDetalhes", p)      
    }

<div class="btn-group pull-right">
    @Html.PageLinks(Model.Paginacao, x => Url.Action("ListaProdutos", new { pagina = x, categoria = Model.CategoriaAtual }))
</div>